favicon: https://s2.loli.net/2022/05/22/4s8QIyo6OEiavVD.png

notice:
  enable: true
  content: æœ¨æœ‰BUGï¼ç«™ç‚¹æ­£å¸¸è¿è¡Œ(ï¾‰ï¾Ÿâˆ€ï¾Ÿ)ï¾‰ | æœ€è¿‘æ›´æ–°ï¼šCè¯­è¨€åŸºç¡€æ•™ç¨‹ | æ›´æ–°æ—¶é—´ï¼š2022-11-03
# æœ¨æœ‰BUGï¼ç«™ç‚¹æ­£å¸¸è¿è¡Œ(ï¾‰ï¾Ÿâˆ€ï¾Ÿ)ï¾‰

tags:
  Git: "#ff4d4d"
  åŸºç¡€æŠ€èƒ½: "#ff99dd"
  ç½‘ç»œçˆ¬è™«: "#ff4d4d"
  Microsoft 5E è®¢é˜…: "#00b300"
  åŸºç¡€è¯­æ³•: "#cc33ff"
  ç‰ˆæœ¬ç®¡ç†å·¥å…·: "#00b300"
  Markdown: "#b35900"
  VScode: "#6699ff"
  Office 365: "#ff944d"
  PicGO: "#6699ff"
  ç¯å¢ƒé…ç½®: "#00b300"
  Python3: "#ffc266"
  Cè¯­è¨€: "#6699ff"
  å›¾åºŠ: "#00b300"
  æ ‡è®°è¯­è¨€: "#4ddbff"
  ä¸€è¨€: "#ff99dd"
  å°¼é‡‡: "#ff3333"
  yunä¸»é¢˜: "#9999ff"
  Hexoåšå®¢: "#ff4d4d"
  Sitemapåœ°å›¾: "#b35900"
  SEOæ”¶å½•: "#ffc266"
  åšå®¢éƒ¨ç½²: "#ff99dd"
  ç™½å«–: "#4ddbff"
  å‰ç½®å‡†å¤‡: "#ff3333"
  é…ç½®é¡¹: "#4ddbff"
  æœç´¢å¼•æ“: "#ffc266"
  Linux: "#ffc266"
  ç³»ç»Ÿæ“ä½œ: "#ff3333"
  Github Calendar: "#cc33ff"
  ç§å¯†: "#808080"
  æµ‹è¯•: "#9999ff"
  Vercel: "#ff944d"
  C++: "#6699ff"
  æŠ€å·§: "#9999ff"

categories:
  ç¼–ç¨‹è¯­è¨€å…¥é—¨: "#ff944d"
  ç¼–ç¨‹æŠ€å·§ä¸ç®—æ³•: "#ff944d"
  ä¸“ä¸šæŠ€èƒ½æ•™ç¨‹: "#cc33ff"
  å…¶ä»–æ•™ç¨‹: "#ffc266"
  ä»£ç ç¼–è¾‘å™¨: "#9999ff"
  å¥½å¥æ‘˜æŠ„: "#66c2ff"
  è‹±æ–‡æ‘˜æŠ„: "#ff99dd"
  å…¶ä»–: "#ff4d4d"

social:
  - name: å¾®ä¿¡(è¯·æ‰«æäºŒç»´ç æ·»åŠ )
    link: https://s2.loli.net/2022/07/20/wzmFPjMJH1eXR4g.jpg
    icon: ri:wechat-2-line
    color: "#1AAD19"
  - name: QQ(è¯·æ‰«æäºŒç»´ç æ·»åŠ )
    link: https://s2.loli.net/2022/07/20/gzCHZvQdkwqLt84.jpg
    icon: ri:qq-line
    color: "#12B7F5"
  - name: GitHub(ä¸ªäººé¡µé¢)
    link: https://github.com/ShengQiBaoZao
    icon: ri:github-line
    color: "#181717"
  - name: E-Mailï¼šlty15376767691@gmail.com
    link: mailto:lty15376767691@gmail.com
    icon: ri:mail-line
    color: "#8E71C1"
  - name: ç½‘æ˜“äº‘éŸ³ä¹(ç‚¹æ­¤è·³è½¬)
    link: https://music.163.com/#/user/home?id=509242587
    icon: ri:netease-cloud-music-line
    color: "#C10D0C"
  - name: Bilibili(ç‚¹æ­¤è·³è½¬)
    link: https://space.bilibili.com/347061710
    icon: ri:bilibili-line
    color: "#FF8EB3"

banner:
  enable: true
  title: åœ£å¥‡å®æ£çš„åšå®¢å°ç«™
  border: true
  cloud:
    enable: true
    color: white
  go_down:
    enable: true
    icon: ri:arrow-down-s-line

say:
  enable: true
  api: https://cdn.jsdelivr.net/gh/ElpsyCN/say@gh-pages/sentences.json
  # https://developer.hitokoto.cn/sentence/
  hitokoto:
    enable: true
    api: https://v1.hitokoto.cn?c=a&c=d&c=e&c=f&c=g&c=i&c=j&c=k

colors:
  primary: "#1975ff"
  bg: "#F5F5F5"
  selection_bg: "#1975ff"
  tag_start_color: "#99bbff"
  tag_end_color: "#1975ff"

mode: time

bg_image:
  enable: true
  url: https://s2.loli.net/2022/05/22/xzK6YApqal2wVSs.png
  dark: https://s2.loli.net/2022/05/22/DkM3WXfSiIq9gmz.jpg
  blur: 5px
  opacity: 0.8

fireworks:
  enable: true
  colors:
    - "102, 167, 221"
    - "62, 131, 225"
    - "33, 78, 194"

scrollreveal:
  enable: true
  targets:
    - .post-card
    - .markdown-body img

cursor:
  enable: true
  default: https://cdn.yunyoujun.cn/css/md-cursors/pointer.cur
  pointer: https://cdn.yunyoujun.cn/css/md-cursors/link.cur
  text: https://cdn.yunyoujun.cn/css/md-cursors/text.cur

sidebar:
  bg_image: https://s2.loli.net/2022/05/22/EjIsa9mV3ecCoT5.jpg
  bg_position: bottom 3rem center
  tagcloud:
    enable: true
    amount: 15

avatar:
  enable: true
  url: https://s2.loli.net/2022/05/22/4s8QIyo6OEiavVD.png
  rounded: true
  opacity: 1
  mickey_mouse: false
  status:
    enable: true
    emoji: ğŸ˜‡
    message: åŠ ç­å‡å¤©ä¸­

menu:
  home:
    path: /
    icon: ri:home-4-line
  list:
    - type: archives
      path: /archives/
      icon: ri:archive-line
    - type: categories
      path: /categories/
      icon: ri:folder-2-line
    - type: tags
      path: /tags/
      icon: ri:price-tag-3-line
    # - path: https://www.yunyoujun.cn
    #   icon: ri:cloud-line
    #   count: ä½ çŒœ
  custom:
    title: ç•™è¨€æ¿
    path: /comment/
    icon: ri:clipboard-line

pages:
  - name: æˆ‘çš„å°ä¼™ä¼´ä»¬
    url: /links/
    icon: ri:genderless-line
    color: dodgerblue
  - name: å¯çˆ±çš„å¥³å­©å­
    url: /girls/
    icon: ri:women-line
    color: hotpink
  - name: ç»™ç‚¹ç»™ç‚¹~
    url: /donate/
    icon: ri:hand-coin-line
    color: "#ff944d"

post_meta:
  item_text: true
  created_at: true
  updated_at: true
  categories: true
  tags: true

toc:
  list_number: true
  max_depth: 6
  min_depth: 1
  placeholder: å¾ˆé—æ†¾ï¼Œè¿™ç¯‡æ–‡ç« å†…å®¹è¾ƒçŸ­ä¸éœ€è¦ç›®å½•æˆ–å’±æ‡’å¾—å†™ç›®å½•
  collapse: true

codeblock:
  copy_btn: true

creative_commons:
  license: by-nc-sa
  post: true
  language: deed.zh
  clipboard: false

lazyload:
  enable: true

reward:
  enable: true
  icon: ri:hand-coin-line
  comment: æ‰‹å¤´é˜”ç»°?ç‚¹è¿™ç‚¹è¿™!moneyå¾—æ–¯!
  methods:
    - name: å¾®ä¿¡æ”¯ä»˜
      path: https://s2.loli.net/2022/07/20/wWSp6bRENMGsDCj.png
      color: "#2DC100"
      icon: ri:wechat-pay-line
    - name: æ”¯ä»˜å®
      path: https://s2.loli.net/2022/07/20/MaiIDcuVsqUWgyF.jpg
      color: "#00A3EE"
      icon: ri:alipay-line
    - name: QQ æ”¯ä»˜
      path: https://s2.loli.net/2022/07/20/Gqv92cabdg4OWkS.png
      color: "#12B7F5"
      icon: ri:qq-line

footer:
  since: 2022
  powered:
    enable: false
  icon:
    name: ri:cloud-line
    animated: true
    color: "#0078E7"
  live_time:
    enable: true
    prefix: æœ¬åšå®¢å·²å†ç»é£éœœåšæŒäº†
    suffix: (ï¿£â–½ï¿£)ï¼
    start_time: "2022-04-15T09:43:00"
  custom_text: '<span>Powered by <a href="https://hexo.io" target="_blank" rel="noopener"><svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="18px" height="18px" viewBox="0 0 512 512" enable-background="new 0 0 512 512" xml:space="preserve" style="vertical-align: middle;margin-right: 4px"><path fill="#0E83CD" d="M256.4,25.8l-200,115.5L56,371.5l199.6,114.7l200-115.5l0.4-230.2L256.4,25.8z M349,354.6l-18.4,10.7l-18.6-11V275H200v79.6l-18.4,10.7l-18.6-11v-197l18.5-10.6l18.5,10.8V237h112v-79.6l18.5-10.6l18.5,10.8V354.6z" data-darkreader-inline-fill="" style="--darkreader-inline-fill:#4cc3ff;"></path></svg>Hexo</a> v6.2.0</span><span class="footer-separator">|</span><span>Theme - <a rel="noopener" href="https://github.com/YunYouJun/hexo-theme-yun" target="_blank"><svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" id="yun-logo" stroke="#000" width="18px" height="18px" viewBox="40 40 320 320" stroke-width="16" style="vertical-align: middle; margin-right: 4px; --darkreader-inline-stroke:#fffffe;" data-darkreader-inline-stroke=""> <defs> <line id="eye" x1="0" y1="-35" x2="0" y2="35" stroke-linecap="round"> <animateTransform attributeName="transform" additive="sum" attributeType="XML" type="scale" from="1 1" to="1 0" dur="0.15s" repeatCount="2"></animateTransform> </line> </defs> <polygon stroke-linejoin="round" fill="none" points="50,250 50,150 100,150 100,100 300,100 300,150 350,150 350,250 300,250 300,300 100,300 100,250 50,250"></polygon> <use xlink:href="#eye" transform="translate(150,200)"></use> <use xlink:href="#eye" transform="translate(250,200)"></use></svg><span>Yun</span></a> v1.10.9</span><div style="height: 8px;"></div>Deploys by<a href="https://vercel.com" target="_blank" rel="noopener noreferrer"><svg width="66.33" height="15" viewBox="0 0 283 64" id="vercel-logo" fill="#000" xmlns="http://www.w3.org/2000/svg" style="vertical-align: middle; --darkreader-inline-fill:#060606;" data-darkreader-inline-fill=""><path d="M141.04 16c-11.04 0-19 7.2-19 18s8.96 18 20 18c6.67 0 12.55-2.64 16.19-7.09l-7.65-4.42c-2.02 2.21-5.09 3.5-8.54 3.5-4.79 0-8.86-2.5-10.37-6.5h28.02c.22-1.12.35-2.28.35-3.5 0-10.79-7.96-17.99-19-17.99zm-9.46 14.5c1.25-3.99 4.67-6.5 9.45-6.5 4.79 0 8.21 2.51 9.45 6.5h-18.9zM248.72 16c-11.04 0-19 7.2-19 18s8.96 18 20 18c6.67 0 12.55-2.64 16.19-7.09l-7.65-4.42c-2.02 2.21-5.09 3.5-8.54 3.5-4.79 0-8.86-2.5-10.37-6.5h28.02c.22-1.12.35-2.28.35-3.5 0-10.79-7.96-17.99-19-17.99zm-9.45 14.5c1.25-3.99 4.67-6.5 9.45-6.5 4.79 0 8.21 2.51 9.45 6.5h-18.9zM200.24 34c0 6 3.92 10 10 10 4.12 0 7.21-1.87 8.8-4.92l7.68 4.43c-3.18 5.3-9.14 8.49-16.48 8.49-11.05 0-19-7.2-19-18s7.96-18 19-18c7.34 0 13.29 3.19 16.48 8.49l-7.68 4.43c-1.59-3.05-4.68-4.92-8.8-4.92-6.07 0-10 4-10 10zm82.48-29v46h-9V5h9zM36.95 0L73.9 64H0L36.95 0zm92.38 5l-27.71 48L73.91 5H84.3l17.32 30 17.32-30h10.39zm58.91 12v9.69c-1-.29-2.06-.49-3.2-.49-5.81 0-10 4-10 10V51h-9V17h9v9.2c0-5.08 5.91-9.2 13.2-9.2z"></path></svg></a><br><img width="315" height="100" src="https://api.moedog.org/count/@ShengQiBaoZao?theme=rule34" style="margin-top:10px" alt>'

post_edit:
  enable: true
  url: https://github.com/ShengQiBaoZao/shengqibaozao_blog/tree/hexo/source/

girls:
  enable: true

comment:
  enable: true
  tips:
    - è‹¥æ‚¨æƒ³åŠæ—¶å¾—åˆ°å›å¤æé†’ï¼Œä¹Ÿå¯ä»¥å»Bç«™ç§ä¿¡æˆ‘å“¦
    - å¦‚æœè¾ƒä¸ºç´§æ€¥ï¼Œå»ºè®®æ·»åŠ å¾®ä¿¡æˆ–QQï¼Œå¹¶æ³¨æ˜æ¥æ„
    - è¯„è®ºç³»ç»Ÿå¯èƒ½åŠ è½½è¾ƒæ…¢ï¼Œè¯·è€å¿ƒç­‰å¾…æˆ–åˆ·æ–°é‡è¯•
  candidates:
    - waline

waline:
  enable: true
  serverURL: https://www.sqbztest2.eu.org
  visitor: false
  comment: true
  emoji:
    - "https://unpkg.com/@waline/emojis@1.0.1/bilibili"
    - "https://unpkg.com/@waline/emojis@1.0.1/weibo"
    - "https://unpkg.com/@waline/emojis@1.0.1/qq"
  locale:
    placeholder: å¡«å†™é‚®ç®±ï¼Œå¯ä»¥æ”¶åˆ°å›å¤é€šçŸ¥å“¦ï½
  requiredMeta: [nick]

engine_search:
  enable: false

local_search:
  enable: true

types:
  link:
    color: "#1975ff"
    icon: ri:external-link-line
  bilibili:
    color: "#FF8EB3"
    icon: ri:bilibili-line
  douban:
    color: "#007722"
    icon: ri:douban-line
  github:
    color: black
    icon: ri:github-line
  netease-cloud-music:
    color: "#C10D0C"
    icon: ri:netease-cloud-music-line
  notion:
    color: black
    icon: ri:notion
  twitter:
    color: "#1da1f2"
    icon: ri:twitter-line
  wechat:
    color: "#1AAD19"
    icon: ri:wechat-2-line
  weibo:
    color: "#E6162D"
    icon: ri:weibo-line
  yuque:
    color: "#25b864"
    icon: ant-design:yuque-outlined
  zhihu:
    color: "#0084FF"
    icon: ri:zhihu-line

wordcount:
  enable: true
  count: true
  time: true

wordcloud:
  enable: true
  height: 750

baidu_push: true

medium_zoom: true

vendors:
  # ä»¥ '/' ç»“å°¾
  host: "https://cdn.jsdelivr.net/npm/"
  # ä¸‹æ–¹ä»£è¡¨è¦†ç›– waline CDN ä¸ºåˆ«çš„é“¾æ¥ï¼Œé»˜è®¤ä¸ç”¨ä¿®æ”¹
  # waline:
  #   css: '@waline/client@v2/dist/waline.css'

pjax:
  enable: true

aplayer:
  global: true
  meting: true
  # https://github.com/metowolf/MetingJS/tree/v1.2#option
  widget:
    enable: true
    autoplay: true
    loop: all
    order: random
    preload: auto
    volume: 0.7
    mutex: true
    lrcType: 0
    listFolded: true
    listMaxHeight: 340px
    audio:
      # - name: æ˜Ÿå®¿è®¡æ—¶
      #   artist: æ‰ç”°æœ—/æ´›å¤©ä¾
      #   url: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/audio/star-timer.mp3
      #   cover: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/bg/stars-timing-0.jpg
    meting:
      enable: true
      id: 7514736165
      server: netease
      type: playlist

widget_tree:
  cdn: true
  hide: false
  layout: default
  # layout:
  #   - home
  #   - page
  showCount: true
  toc:
    enable: false
    # max_depth:
    # min_depth:
    # list_number:
