favicon: https://s2.loli.net/2022/05/22/4s8QIyo6OEiavVD.png

notice:
  enable: true
  content: ç«™ç‚¹æ­£å¸¸è¿è¡Œ(ï¾‰ï¾Ÿâˆ€ï¾Ÿ)ï¾‰ ~è¿‘æœŸå­¦ä¹ ä¸æ›´æ–°ï¼šCè¯­è¨€åŸºç¡€æ•™ç¨‹ã€‚æœ€è¿‘æ›´æ–°æ—¶é—´ï¼š2022-05-29

tags:
  Git: "#ff4d4d"
  ç½‘ç»œçˆ¬è™«: "#ff4d4d"
  Microsoft 5E è®¢é˜…: "#00b300"
  åŸºç¡€è¯­æ³•: "#cc33ff"
  ç‰ˆæœ¬ç®¡ç†å·¥å…·: "#00b300"
  Markdown: "#b35900"
  VScode: "#6699ff"
  Office 365: "#ff944d"
  PicGO: "#6699ff"
  æ•™ç¨‹åˆ†äº«: "#cc33ff"
  ç¯å¢ƒé…ç½®: "#00b300"
  Python3: "#ffc266"
  Cè¯­è¨€: "#6699ff"
  å›¾åºŠ: "#4ddbff"
  æ ‡è®°è¯­è¨€: "#4ddbff"
  ä¸€è¨€: "#ff99dd"
  ç”Ÿæ´»æ„Ÿæ‚Ÿ: "#9999ff"
  ç¬”ä¸‹ç”Ÿè¾‰: "#00b300"
  å°¼é‡‡: "#ff3333"
  yunä¸»é¢˜: "#9999ff"
  Hexoåšå®¢: "#ff4d4d"

categories:
  ç¼–ç¨‹è¯­è¨€: "#ff944d"
  å…¶ä»–æ•™ç¨‹: "#ffc266"
  ä»£ç ç¼–è¾‘å™¨: "#9999ff"
  å¥½å¥æ‘˜æŠ„: "#66c2ff"

social:
  - name: å¾®ä¿¡(è¯·æ‰«æäºŒç»´ç æ·»åŠ )
    link: https://s2.loli.net/2022/05/22/PijGqtNOyW45BvZ.jpg
    icon: ri:wechat-2-line
    color: "#1AAD19"
  - name: QQ(è¯·æ‰«æäºŒç»´ç æ·»åŠ )
    link: https://s2.loli.net/2022/05/22/gktDW5v8RKIYdOn.jpg
    icon: ri:qq-line
    color: "#12B7F5"
  - name: GitHub(ä¸ªäººé¡µé¢)
    link: https://github.com/ShengQiBaoZao
    icon: ri:github-line
    color: "#181717"
  - name: E-Mail:lty15376767691@gmail.com
    link: mailto:lty15376767691@gmail.com
    icon: ri:mail-line
    color: "#8E71C1"
  - name: ç½‘æ˜“äº‘éŸ³ä¹(ç‚¹æ­¤è·³è½¬)
    link: https://music.163.com/#/user/home?id=509242587
    icon: ri:netease-cloud-music-line
    color: "#C10D0C"
  - name: Bilibili(ç‚¹æ­¤è·³è½¬)
    link: https://space.bilibili.com/347061710
    icon: ri:bilibili-line
    color: "#FF8EB3"

banner:
  enable: true
  title: åœ£å¥‡å®æ£çš„åšå®¢å°ç«™
  border: true
  cloud:
    enable: true
    color: white
  go_down:
    enable: true
    icon: ri:arrow-down-s-line

colors:
  primary: "#1975ff"
  bg: "#F5F5F5"
  selection_bg: "#7373ff"
  tag_start_color: "#99bbff"
  tag_end_color: "#1975ff"

mode: auto

bg_image:
  enable: true
  url: https://s2.loli.net/2022/05/22/xzK6YApqal2wVSs.png
  dark: https://s2.loli.net/2022/05/22/DkM3WXfSiIq9gmz.jpg
  blur: 5px
  opacity: 0.8

fireworks:
  enable: true
  colors:
    - "102, 167, 221"
    - "62, 131, 225"
    - "33, 78, 194"

scrollreveal:
  enable: true
  targets:
    - .post-card
    - .markdown-body img

cursor:
  enable: true
  default: https://cdn.yunyoujun.cn/css/md-cursors/pointer.cur
  pointer: https://cdn.yunyoujun.cn/css/md-cursors/link.cur
  text: https://cdn.yunyoujun.cn/css/md-cursors/text.cur

sidebar:
  bg_image: https://s2.loli.net/2022/05/22/EjIsa9mV3ecCoT5.jpg
  bg_position: bottom 3rem center
  tagcloud:
    enable: true
    amount: 15

avatar:
  enable: true
  url: https://s2.loli.net/2022/05/22/4s8QIyo6OEiavVD.png
  rounded: true
  opacity: 1
  mickey_mouse: false
  status:
    enable: true
    emoji: ğŸ˜‡
    message: åŠ ç­å‡å¤©ä¸­

menu:
  home:
    path: /
    icon: ri:home-4-line
  list:
    - type: archives
      path: /archives/
      icon: ri:archive-line
    - type: categories
      path: /categories/
      icon: ri:folder-2-line
    - type: tags
      path: /tags/
      icon: ri:price-tag-3-line
    # - path: https://www.yunyoujun.cn
    #   icon: ri:cloud-line
    #   count: ä½ çŒœ
  custom:
    title: ç•™è¨€æ¿
    path: /comment/
    icon: ri:clipboard-line

pages:
  - name: æˆ‘çš„å°ä¼™ä¼´ä»¬
    url: /links/
    icon: ri:genderless-line
    color: dodgerblue
  - name: æœ¬é¡¹ç›®ä»“åº“(æ±‚Star!!)
    url: https://github.com/ShengQiBaoZao/shengqibaozao_blog
    icon: ri:github-line
    color: orange
  - name: å¯çˆ±çš„å¥³å­©å­
    url: /girls/
    icon: ri:women-line
    color: hotpink

post_meta:
  item_text: true
  created_at: true
  updated_at: true
  categories: true
  tags: true

toc:
  list_number: true
  max_depth: 6
  min_depth: 1
  placeholder: å¾ˆé—æ†¾ï¼Œè¿™ç¯‡æ–‡ç« å†…å®¹è¾ƒçŸ­ä¸éœ€è¦ç›®å½•æˆ–å’±æ‡’å¾—å†™ç›®å½•
  collapse: true

codeblock:
  copy_btn: true

creative_commons:
  license: by-nc-sa
  post: true
  language: deed.zh
  clipboard: false

lazyload:
  enable: true

reward:
  enable: true
  icon: ri:hand-coin-line
  comment: åˆ›ä½œä¸æ˜“ï¼Œå¦‚æœå¯¹ä½ æœ‰å¸®åŠ©ï¼Œç‚¹æ­¤æ‰“èµæ”¯æŒ
  methods:
    - name: æ”¯ä»˜å®
      path: https://s2.loli.net/2022/05/22/Zz73mGbyuJMWqrj.jpg
      color: "#00A3EE"
      icon: ri:alipay-line
    - name: QQ æ”¯ä»˜
      path: https://s2.loli.net/2022/05/22/duCQVgIl2yJqwfO.png
      color: "#12B7F5"
      icon: ri:qq-line
    - name: å¾®ä¿¡æ”¯ä»˜
      path: https://s2.loli.net/2022/05/22/vMCFmPrxBoSJsUE.png
      color: "#2DC100"
      icon: ri:wechat-pay-line

footer:
  since: 2022
  icon:
    name: ri:cloud-line
    animated: true
    color: "#0078E7"
  live_time:
    enable: true
    prefix: æœ¬åšå®¢å·²èŒèŒå“’åœ°è¿è¡Œ
    suffix: (â—'â—¡'â—)
    start_time: "2022-04-15T09:43:00"

girls:
  enable: true

comment:
  enable: true
  tips:
    - è‹¥æ‚¨æƒ³åŠæ—¶å¾—åˆ°å›å¤æé†’ï¼Œä¹Ÿå¯ä»¥å»Bç«™ç§ä¿¡æˆ‘å“¦
    - å¦‚æœè¾ƒä¸ºç´§æ€¥ï¼Œå»ºè®®æ·»åŠ å¾®ä¿¡æˆ–QQï¼Œå¹¶æ³¨æ˜æ¥æ„
    - è¯„è®ºç³»ç»Ÿå¯èƒ½åŠ è½½è¾ƒæ…¢ï¼Œè¯·è€å¿ƒç­‰å¾…æˆ–åˆ·æ–°é‡è¯•
  candidates:
    - waline

waline:
  enable: true
  serverURL: https://waline-swart-ten.vercel.app/
  visitor: true
  comment: true

engine_search:
  enable: false

local_search:
  enable: true

wordcount:
  enable: true
  count: true
  time: true

wordcloud:
  enable: true
  height: 750

baidu_push: true

medium_zoom: true
