favicon: https://fastly.jsdelivr.net/gh/ShengQiBaoZao/Image/user2.png

social:
  - name: QQ
    link: https://fastly.jsdelivr.net/gh/ShengQiBaoZao/Image/QQ.jpg
    icon: icon-qq-line
    color: "#12B7F5"
  - name: GitHub
    link: https://github.com/ShengQiBaoZao
    icon: icon-github-line
    color: "#181717"
  - name: E-Mail
    link: mailto:lty15376767691@gmail.com
    icon: icon-mail-line
    color: "#8E71C1"
  - name: ç½‘æ˜“äº‘éŸ³ä¹
    link: https://music.163.com/#/user/home?id=509242587
    icon: icon-netease-cloud-music-line
    color: "#C10D0C"
  - name: Bilibili
    link: https://space.bilibili.com/347061710
    icon: icon-bilibili-line
    color: "#FF8EB3"
  - name: å¾®ä¿¡
    link: https://fastly.jsdelivr.net/gh/ShengQiBaoZao/Image/wechat.jpg
    icon: icon-wechat-2-line
    color: "#1AAD19"

banner:
  enable: true
  title: åœ£å¥‡å®æ£çš„å°ç«™
  border: true
  cloud:
    enable: true
    color: white
  go_down:
    enable: true
    icon: icon-arrow-down-s-line

notice:
  enable: true
  content: ç«™ç‚¹æµ‹è¯•ä¸­ã€‚ã€‚ã€‚

mode: auto

bg_image:
  enable: true
  url: https://fastly.jsdelivr.net/gh/ShengQiBaoZao/Image/background.png
  dark: https://fastly.jsdelivr.net/gh/ShengQiBaoZao/Image/background6.jpg
  blur: 5px
  opacity: 0.8

fireworks:
  enable: true
  colors:
    - "102, 167, 221"
    - "62, 131, 225"
    - "33, 78, 194"

scrollreveal:
  enable: true
  targets:
    - .post-card
    - .markdown-body img

cursor:
  enable: false
  default: https://cdn.yunyoujun.cn/css/md-cursors/pointer.cur
  pointer: https://cdn.yunyoujun.cn/css/md-cursors/link.cur
  text: https://cdn.yunyoujun.cn/css/md-cursors/text.cur

sidebar:
  bg_image: https://fastly.jsdelivr.net/gh/YunYouJun/cdn/img/bg/stars-timing-1.jpg
  bg_position: bottom 3rem center
  tagcloud:
    enable: false
    amount: 20

avatar:
  enable: true
  url: https://fastly.jsdelivr.net/gh/ShengQiBaoZao/Image/user2.png
  rounded: true
  opacity: 1
  mickey_mouse: false
  status:
    enable: true
    emoji: ğŸ˜‡
    message: åŠ ç­å‡å¤©ä¸­

menu:
  home:
    path: /
    icon: icon-home-4-line
  list:
    - type: archives
      path: /archives/
      icon: icon-archive-line
    - type: categories
      path: /categories/
      icon: icon-folder-2-line
    - type: tags
      path: /tags/
      icon: icon-price-tag-3-line
    # - path: https://www.yunyoujun.cn
    #   icon: icon-cloud-line
    #   count: ä½ çŒœ
  custom:
    title: æœ¬é¡¹ç›®ä»“åº“
    path: https://github.com/ShengQiBaoZao/shengqibaozao.github.io
    icon: icon-github-line

pages:
  - name: æˆ‘çš„å°ä¼™ä¼´ä»¬
    url: /links/
    icon: icon-genderless-line
    color: dodgerblue
  - name: å¯çˆ±çš„å¥³å­©å­
    url: /girls/
    icon: icon-women-line
    color: hotpink

post_meta:
  item_text: false
  created_at: true
  updated_at: true
  categories: true
  tags: true

toc:
  list_number: true
  max_depth: 4
  min_depth: 1
  placeholder: å¾ˆé—æ†¾ï¼Œè¿™ç¯‡æ–‡ç« å†…å®¹è¾ƒçŸ­ä¸éœ€è¦ç›®å½•æˆ–å’±æ‡’å¾—å†™ç›®å½•
  collapse: false

codeblock:
  copy_btn: true

creative_commons:
  license: by-nc-sa
  post: true
  language: deed.zh
  clipboard: false

lazyload:
  enable: true

reward:
  enable: true
  icon: icon-hand-coin-line
  comment: åˆ›ä½œä¸æ˜“ï¼Œå¦‚æœå¯¹ä½ æœ‰å¸®åŠ©ï¼Œç‚¹æ­¤æ‰“èµæ”¯æŒ
  methods:
    - name: æ”¯ä»˜å®
      path: https://fastly.jsdelivr.net/gh/ShengQiBaoZao/Image/alipay.jpg
      color: "#00A3EE"
      icon: icon-alipay-line
    - name: QQ æ”¯ä»˜
      path: https://fastly.jsdelivr.net/gh/ShengQiBaoZao/Image/QQpay.png
      color: "#12B7F5"
      icon: icon-qq-line
    - name: å¾®ä¿¡æ”¯ä»˜
      path: https://fastly.jsdelivr.net/gh/ShengQiBaoZao/Image/wechatpay.png
      color: "#2DC100"
      icon: icon-wechat-pay-line

footer:
  since: 2022
  icon:
    name: icon-cloud-line
    animated: true
    color: "#0078E7"
  live_time:
    enable: true
    prefix: æœ¬åšå®¢å·²èŒèŒå“’åœ°è¿è¡Œ
    suffix: (â—'â—¡'â—)
    start_time: "2022-04-15T09:43:00"

girls:
  enable: true

comment:
  enable: true
  tips:
    - è‹¥æ‚¨æƒ³åŠæ—¶å¾—åˆ°å›å¤æé†’ï¼Œä¹Ÿå¯ä»¥å»Bç«™ç§ä¿¡æˆ‘å“¦
    - å¦‚æœè¾ƒä¸ºç´§æ€¥ï¼Œå»ºè®®æ·»åŠ å¾®ä¿¡æˆ–QQï¼Œå¹¶æ³¨æ˜æ¥æ„
    - å»ºè®®é»˜è®¤ä½¿ç”¨Valineè¯„è®ºï¼Œå‡ºç°é”™è¯¯è¯·ä½¿ç”¨Livereè¯„è®º
  candidates:
    - valine
    - livere

valine:
  enable: true
  appId: SYoVU6j10s1vQJW8qq4o2YNN-MdYXbMMI
  appKey: lXveRnVuQRUCa7HlP395OcHL
  placeholder: è¯´ç‚¹ä»€ä¹ˆï¼Ÿ
  avatar:
  meta:
    - nick
    - mail
    - link
  pageSize: 10 # pagination size

livere:
  enable: true
  uid: MTAyMC81NTQ1OC8zMTkyNQ==

engine_search:
  enable: false

local_search:
  enable: true

busuanzi:
  enable: true
  site_uv: true
  site_uv_icon: icon-user-line
  site_pv: true
  site_pv_icon: icon-eye-line
  page_pv: true
  page_pv_icon: icon-eye-line

wordcount:
  enable: true
  count: true
  time: true